# This file contains the credentials for the voice & chat platforms
# which your bot is using.
# https://rasa.com/docs/rasa/user-guide/messaging-and-voice-channels/

rest:
#  # you don't need to provide anything here - this channel doesn't
#  # require any credentials


telegram:
  access_token: "1328696437:AAFn4uNTpQQ0-qbLVO_1vf0ilWPXK7K_Psc"
  verify: "Coronasafe_kerala_bot"
  webhook_url: "https://coronasafe-bot.herokuapp.com/webhooks/telegram/webhook"

facebook:
  verify: "CoronaSafe_Kerala_Bot"
  secret: "88328727b4010f5ced5f6516ee73330c"
  page-access-token: "EAAJZCU4VnKYQBAPOJfYZC4ZBhRuMjuXX8p9W5sEU92qxqhPu2Mt3ZCEUqGTuzZAete9YBTZBOqABNpgOfTDb8sYmYv7X31YL9Dsorbxf24ouE5hcOSyIFWAQCXx6KmDHxrNbzhZAjRSaNs2GSXhbZAquiV89VvUKlu5Kv1GS7JV5agZDZD"

#slack:
#  slack_token: "<your slack token>"
#  slack_channel: "<the slack channel>"

#socketio:
#  user_message_evt: <event name for user message>
#  bot_message_evt: <event name for but messages>
#  session_persistence: <true/false>

#mattermost:
#  url: "https://<mattermost instance>/api/v4"
#  token: "<bot token>"
#  webhook_url: "<callback URL>"

# This entry is needed if you are using Rasa X. The entry represents credentials 
# for the Rasa X "channel", i.e. Talk to your bot and Share with guest testers.
rasa:
  url: "http://localhost:5002/api"
